# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Save with Sanders
email: rogermparent@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is a simple web application to calculate how much tax 
  a person pays under Bernie Sanders' tax plan
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://savewithsanders.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Minification
compress_html:
  comments: ["/*", "*/", "<--", "-->"]
  blanklines: false

# Input Categories
# These are practically ripped straight from berniecalc.com
input-categories:
  - title: Personal Income
    inputs:
    - Income
  - title: Speculative Income
    inputs:
    - Income from Capital Gains
    - Income from Stocks
    - Income from Derivatives
    - Income from Bonds
  - title: Estate Income
    inputs:
    - Inheritance Size
    - Net Wealth
  - title: Student Loans
    inputs:
    - Amount in Student Loans
    - Student Loan Rate
    - Months left until repaid
  - title: Family Expenses
    inputs:
    - Number of Dependents
    - Monthly Health Insurance Payments
